accessory_app_template/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root :to => 'manufacturers#index'

  resources :emails, only: [:edit, :update]

  resources :manufacturers do
    resources :models
  end
  resources :models do
    resources :accessories
  end

  resources :order_items, only: [:create, :update, :destroy]
  resource :cart, only: [:show]
  resources :youre_done, only: [:index]
  resources :associates do
    resource :checkouts, only: [:create]
  end

  resources :charges
  resources :console
  resources :charts do
    collection do
      get 'sales'
    end
  end

end

accessory_app_template/app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  def index
    @checkouts = Checkout.all
  end
end

accessory_app_template/app/views/console/_console_nav.html.erb
<nav class="navbar">
  <div class="container-fluid col-md-12">
    <ul class="nav navbar-nav console-nav">
      <li><%= link_to "Stats", console_index_path %></li>
      <li><%= link_to "Emails", edit_email_path(id: 1) %></li>
      <li><%= link_to "Account", edit_admin_registration_path %></li>
    </ul>
  </div>
</nav>

accessory_app_template/app/views/console/index.html.erb
<%= render "shared/navbar" %>

<%= render "console_nav" %>
<script type="text/javascript">
$(function () {
  $('#container').highcharts({
      title:    { text: 'Monthly Accessory Sales', x: -20 },
      subtitle: { text: 'Last 30 days', x: -20 },
      xAxis:    {
        type: "datetime",
        dateTimeLabelFormats: {
            month: '%e. %b',
            year: '%b'
        },
        title: {
            text: 'Date'
        }
      },
      yAxis:    {
        title: {
          text: 'Dollars'
        },
        plotLines: [{
          value: 0,
          width: 1,
          color: '#808080'
        }]
      },
      tooltip: {
        formatter: function() {
          return Highcharts.dateFormat("%B %e, %Y", this.x) + ': ' + "$" + Highcharts.numberFormat(this.y, 2);
        }
      },
      legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle',
        borderWidth: 0
      },
      series: [{
        pointInterval: <%= 1.day * 1000%>,
        pointStart: <%= 4.weeks.ago.to_i * 1000 %>,
        name: 'Revenue',
        data: <%= (4.weeks.ago.to_date..Date.today).map { |date| Checkout.total_on(date).to_f }.inspect %>
      }]
  });
});
</script>
<div id="container"></div>





<!-- <%= line_chart sales_charts_path %> -->