accessory_app_template/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root :to => 'manufacturers#index'

  resources :emails, only: [:edit, :update]

  resources :manufacturers do
    resources :models
  end
  resources :models do
    resources :accessories
  end

  resources :order_items, only: [:create, :update, :destroy]
  resource :cart, only: [:show]
  resources :youre_done, only: [:index]
  resources :associates do
    resource :checkouts, only: [:create]
  end

  resources :charges
  resources :console
  resources :charts do
    collection do
      get 'sales'
    end
  end

end

accessory_app_template/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :models
  validates :name, presence: true
end

accessory_app_template/app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    @model = Model.new
    if session[:order_id] = nil
      Order.find(session[:order_id]).destroy
    else
      Order.new
    end
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = "Manufacturer created successfully"
      redirect_to manufacturers_path
    else
      render :new
    end
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
    if $manufacturer.update(manufacturer_params)
      redirect_to manufacturers_path
    else
      render :edit
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy
    redirect_to manufacturers_path
  end

private
  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

accessory_app_template/app/views/manufacturers/_form.html.erb
<div class="admin-controls">
  <h3>Admin controls (Manufacturers):</h3>
  <% render "layouts/errors", :object => @manufacturer %>

  <%= bootstrap_form_for @manufacturer do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>

accessory_app_template/app/views/manufacturers/index.html.erb
<%= render 'shared/navbar' %>
<div class="row row-centered">
  <div class="col-xs-12 col-centered">
    <ul class="manufacturer-buttons">
      <%= link_to manufacturer_path(@manufacturers.find(1)) do %>
        <%= image_tag "toyota-of-corvallis.jpg", class: "logo-button-toyota" %>
      <% end %>
      <%= link_to manufacturer_path(@manufacturers.find(2)) do %>
        <%= image_tag "subaru-of-corvallis-logo.jpg", class: "logo-button-subaru" %>
      <% end %>
    </ul>
  </div>
</div>

<!-- <% @manufacturers.each do |manufacturer| %>
  <%= link_to manufacturer.name, manufacturer_path(manufacturer), class: "btn btn-lg btn-custom-manufacturer" %>
<% end %> -->

<!-- <div class="admin-controls">
  <p><%= link_to "Add manufacturer", new_manufacturer_path %></p>
</div> -->

accessory_app_template/app/views/manufacturers/new.html.erb
<%= render 'form' %>

accessory_app_template/app/views/manufacturers/show.html.erb
<div class="page-header col-xs-12">
  <h1>
    <%= link_to manufacturers_path do %>
      Select your <%= @manufacturer.name %> model
    <% end %>
    <% if admin_signed_in? %>
      <small>
        <%= link_to 'Add Model', new_manufacturer_model_path(@manufacturer, @model), id: "add_link" %>
      </small>
    <% end %>
  </h1>
</div>

<% if @manufacturer.models.any? %>

      <% @manufacturer.models.each do |model| %>
        <%= link_to manufacturer_model_path(@manufacturer, model) do %>
          <div class="cards col-md-12">
            <div class="row">
              <div class="model-image col-xs-4">
                <%= image_tag model.image.url(:large), class: "large-image" %>
              </div>
              <div class="model-year-name">
                <div class="model-year col-xs-2">
                  <%= model.year %>
                </div>
                <div class="model-name col-xs-2">
                  <%= model.name %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% if admin_signed_in? %>
          <div class="admin-controls edit-model col-xs-5">
            <%= link_to 'edit', edit_manufacturer_model_path(@manufacturer, model) %>
          </div>
        <% end %>
      <% end %>

<% end %>