accessory_app_template/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root :to => 'manufacturers#index'

  resources :emails, only: [:edit, :update]

  resources :manufacturers do
    resources :models
  end
  resources :models do
    resources :accessories
  end

  resources :order_items, only: [:create, :update, :destroy]
  resource :cart, only: [:show]
  resources :youre_done, only: [:index]
  resources :associates do
    resource :checkouts, only: [:create]
  end

  resources :charges
  resources :console
  resources :charts do
    collection do
      get 'sales'
    end
  end

end

accessory_app_template/app/models/accessory.rb
class Accessory < ActiveRecord::Base
  belongs_to :model
  has_many :order_items, :dependent => :destroy

  default_scope { where(active: true) }

  has_attached_file :image,
    :preserve_files => "true",
    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }
  validates_attachment :image, :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

  def full_price
    self.price + self.labor_cost
  end

  def discount
    if self.price != nil
      (self.price * 0.85) + self.labor_cost
    end
  end

  def monthly
    if self.discount != nil
      (self.discount * (1 + 0.1 * 5))/60
    end
  end
end

accessory_app_template/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

accessory_app_template/app/models/associate.rb
class Associate < ActiveRecord::Base
  has_many :checkouts
  validates :name, presence: true
end

accessory_app_template/app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :associate
  belongs_to :order

  def self.total_on(date)

    # Order.joins(:checkout).where("date(orders.created_at) IN (?)", date).sum(:subtotal)
    Checkout.joins(:order).where("date(orders.created_at) = (?)", date).sum(:subtotal)
    # Order.joins(:checkout).where(orders: { created_at: [date]}).sum(:subtotal)

    # ActiveRecord::Base.connection.execute(
    #   "SELECT SUM(subtotal)
    #   FROM orders
    #   INNER JOIN checkouts
    #   ON orders.id = checkouts.order_id
    #   WHERE (date(checkouts.created_at) IN '#{date}')"
    # )
  end
end




# order.collect { |oi| oi.subtotal }.sum

# Checkout.joins(:order).where("date(orders.created_at) = (?)", date).sum(:subtotal)

# SELECT SUM(subtotal) FROM "checkouts" INNER JOIN "orders" ON "orders"."id" = "checkouts"."order_id" WHERE (date(orders.created_at) = '2015-04-23','2015

# ActiveRecord::Base.connection.execute(
#   "SELECT SUM(subtotal)
#   FROM orders
#   INNER JOIN checkouts
#   ON orders.id = checkouts.order_id
#   WHERE (date(checkouts.created_at) = '#{begin_date}', '#{end_date}')"
# )
# checkout_orders = []
# self.all.each do |checkout_order|
#   order = Order.find(checkout_order.order_id)
#   checkout_orders.push(order)
# end
# checkout_orders.where("date(created_at) = ?", date).sum(:subtotal)

accessory_app_template/app/models/email.rb
class Email < ActiveRecord::Base
  validates :address, presence: true
end

accessory_app_template/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :models
  validates :name, presence: true
end

accessory_app_template/app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :manufacturer
  has_many :accessories
  validates :name, presence: true
  validates :year, presence: true

  has_attached_file :image, :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }
  validates_attachment :image, :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

accessory_app_template/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items, :dependent => :destroy
  has_one :checkout
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def monthly_subtotal
    order_items.collect { |oi| oi.monthly_price }.sum
  end

  # def total_on(date)
  #   where("date(created_at) = ?", date).sum(:subtotal)
  # end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

accessory_app_template/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :accessory_present
  validate :order_present

  before_save :finalize

# unit_price ensures the price on the page is what the customer pays. If the price
# is changed in the database while the customer is checking out, it will not
# change the final price.
  def unit_price
    accessory.price + accessory.labor_cost
  end

  def total_price
    unit_price * quantity
  end

  def monthly_price
    accessory.monthly
  end

private
  def accessory_present
    if accessory.nil?
      errors.add(:accessory, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
    self[:monthly_price] = monthly_price
  end
end

accessory_app_template/app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders, :dependent => :destroy
end

accessory_app_template/app/controllers/models_controller.rb
class ModelsController < ApplicationController

  def new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @model = Model.new
  end

  def show
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @model = @manufacturer.models.find(params[:id])
    # creates new instance of order_item for use in forms
    @order_item = current_order.order_items.new
  end

  def create
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @model = @manufacturer.models.new(model_params)
    if @model.save
      flash[:notice] = "Model submitted"
      redirect_to manufacturer_path(@model.manufacturer)
    else
      render :new
    end
  end

  def edit
    # @manufacturer = Manufacturer.find(params[:manufacturer_id])
    # @model = @manufacturer.models.find(params[:id])
    @model = Model.find(params[:id])
  end

  def update
    # @manufacturer = Manufacturer.find(params[:manufacturer_id])
    # @model = @manufacturer.models.find(params[:id])
    @model = Model.find(params[:id])
    if @model.update(model_params)
      flash[:notice] = "Your model has been changed successfully"
      redirect_to root_path
    else
      flash[:error] = "There was an error with your edit"
      render action: :edit
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @model = @manufacturer.models.find(params[:id])
    if @model.destroy
      flash[:notice] = "Your model has been deleted"
    else
      flash[:error] = "There was an error when deleting"
    end
    redirect_to manufacturer_path(@manufacturer)
  end


private
  def model_params
    params.require(:model).permit(:name, :year, :image)
  end
end

accessory_app_template/app/views/models/_decline.html.erb
<div class="decline cards col-xs-12 col-md-12" >
  <div class="row" id="396">
    <div class="accessory-image col-xs-12 col-md-4">
      <%= image_tag "no-thank-you-.jpg", class: "large-image" %>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="accessory-name">
        I do not want to order accessories at this time.
      </div>
    </div>
    <div class="price-and-button col-xs-12 col-md-2">
      <%= form_for @order_item, remote: true do |f| %>
        <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :accessory_id, value: 396 %>
        <div class="decline_button">
          <%= f.submit "Decline", class: "btn btn-danger decline-button" %>
        </div>
        <div class="remove decline-remove">
        </div>
      <% end %>
    </div>
  </div>
</div>

accessory_app_template/app/views/models/_form.html.erb
<%= render 'layouts/errors', object: @model %>

<%= bootstrap_form_for [@manufacturer, @model], :url => manufacturer_models_path, :html => { :multipart => true } do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :year %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

accessory_app_template/app/views/models/edit.html.erb
<%= render 'layouts/errors', object: @model %>
<div class="page-header">
  <h1><%= link_to "Edit " + @model.name, manufacturers_path %></h1>
</div>

<div class="admin-controls col-xs-12 col-md-6 col-md-offset-3">
  <%= image_tag @model.image.url(:large), class: "large-image" %>
  <%= render 'form' %>
</div>

accessory_app_template/app/views/models/new.html.erb
<div class="admin-controls">
  <h3>Admin controls. Add new <%= @manufacturer.name %> model:</h3>
  <%= render 'form' %>
</div>

accessory_app_template/app/views/models/show.html.erb
<div class="page-header">
  <h1>
    <%= link_to root_path do %>
      <%= @model.year %> <%= @model.name %> Accessories
    <% end %>
    <% if admin_signed_in? %>
      <small>
        <%= link_to 'Add Accessory', new_model_accessory_path(@model, @accessory), id: "add_link" %>
      </small>
    <% end %>
  </h1>
</div>


<% if @model.accessories.any? %>
  <% @model.accessories.each do |accessory| %>
    <div class="cards col-xs-12 col-md-12">
      <div class="row" id="<%= accessory.id %>">
        <div class="accessory-image col-xs-12 col-md-4">
          <%= image_tag accessory.image.url(:large), class: "large-image" %>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="accessory-name">
            <%= accessory.name %>
          </div>
          <div class="accessory-description">
            <%= accessory.description %>
          </div>
        </div>
        <div class="price-and-button col-xs-12 col-md-2">
          <%= form_for @order_item, remote: true do |f| %>
            <div class="price-and-price-per-month">
              <div class="price">
                <h4><%= number_to_currency accessory.full_price %></h4>
                <% if accessory.labor_cost > 0 %>
                  <p>Includes <%= number_to_currency accessory.labor_cost %> labor</p>
                <% end %>
              </div>
              <!-- <div class="price-discount">
                <h4><%= number_to_currency accessory.discount %></h4>
              </div> -->
              <div class="price-per-month">
                <h4><%= number_to_currency accessory.monthly %>/mo. *</h4>
              </div>
            </div>
            <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
            <%= f.hidden_field :accessory_id, value: accessory.id %>
            <div class="add">
              <%= f.submit "Add", class: "btn btn-primary add-button" %>
            </div>
            <div class="remove">
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% if admin_signed_in? %>
      <div class="admin-controls edit-accessory col-md-2">
        <%= link_to 'edit', edit_model_accessory_path(@model, accessory ) %> | <%= link_to 'delete', model_accessory_path(@model, accessory), data: { confirm: "This will permenately delete this accessory. Are you sure?", method: "delete" } %></li>
      </div>
    <% end %>
  <% end %>
  <%= render 'decline' %>
<% end %>

<div class="navbar navbar-fixed-bottom" role="navigation">
  <div class="container-fluid checkout-bar">
    <div class="row">
      <div class="back col-xs-3 col-md-3">
        <%= link_to "Back", :back, class: "btn btn-success back-button" %>
      </div>
      <div class="col-xs-9 col-md-6 cart-text">
<%= render 'layouts/cart_text' %>
      </div>
      </div>
    <div class="asterix">
      * Monthly price is an estimate based on 10% APR for 60 months. Speak with dealer representative for price including tax, installation, and other interest rates.
    </div>
  </div>
</div>